version: "2"

services:
  zookeeper:
    image: "docker.io/bitnami/zookeeper:3-debian-10"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'kc_zookeeper_data:/bitnami'
  kafka_broker_1:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_broker_1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - "kc_data_1:/bitnami"
    depends_on:
      - zookeeper
  kafka_broker_2:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "19092:19092"
      - "19093:19093"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_broker_2:19092,EXTERNAL://localhost:19093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - "kc_data_2:/bitnami"
    depends_on:
      - zookeeper
  kafka_broker_3:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "29092:29092"
      - "29093:29093"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_broker_3:29092,EXTERNAL://localhost:29093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - "kc_data_3:/bitnami"
    depends_on:
      - zookeeper
  cmak:
    image: "iunera/cmak"
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  # kc: kafka cluster
  kc_zookeeper_data:
    driver: local
  kc_data_1:
    driver: local
  kc_data_2:
    driver: local
  kc_data_3:
    driver: local
