/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.yamashiro0110.example.kafka;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class KafkaProducerApp {

    public static void main(final String[] args) {
        SpringApplication.run(KafkaProducerApp.class, args);
    }
}
